name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3 # PaulHatch/semantic-version@v4.0.3 es una accion de un tercero que estamos usando, y nos permite poder automatizar el versionamiento de nuestra aplicacion
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version # Agregamos este id para poder usar este step o paso de versionamiento en otros steps, en otras palabras sirve como referencia

    - name: Docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }} # Este es mi usuario de docker que es jonyplo
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # Este password es el token que cree en mi cuenta de docker
      run: | # Este simbolo | es necesario para poner varios comandos uno debajo el otro
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "New version: $NEW_VERSION !!!!!!!!!!!"
        
    - name: Build Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }} # En esta nueva variable de entorno busco en los "steps" el que tiene como referencia el id "version" y dentro de este step busco el "output" llamado "version" que es algo propio de la accion PaulHatch/semantic-version@v4.0.3 que estamos usando en este step
      run: |
        docker build -t jonyplo/docker-graphql:$NEW_VERSION .
        docker build -t jonyplo/docker-graphql:latest .

    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push jonyplo/docker-graphql:$NEW_VERSION
        docker push jonyplo/docker-graphql:latest
        
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
